# Generated by Django 3.1.2 on 2020-12-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201224_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='banner',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='banner',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
